[project]
name = "advent-of-code-2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "plotly>=5.18",
 "kaleido>=0.2",
 "sortedcontainers>=2.4.0",
]
